%=========================================================================
%       BY: YEMAN BRHANE HAGOS and
%           MINH VU
%=========================================================================
clc;
close all;
clear all;

%% ******************** CREATE fIGURE ****************************************

F= figure('Position',[100 50 1066 700],...
   'Name','',...
   'menubar','none','resize','off',...
   'NumberTitle','off');


Background=get(F,'Color');
%TITLE
 Title= uicontrol('parent',F,'Style','text','Position',[250 650 500 50],...
     'string','FACE RECOGNITION', 'background', Background ,...
     'horizontalAlignment','center', 'FontSize',14,'FontWeight','bold');
%% Panels

% FOR BUTTONS
panel = uipanel('parent',F,'Title','','FontSize',12,...
    'BackgroundColor',Background,...
    'units','pixel','Position',[0 0 330 650]);
% FOR AXES
Wp=300;
Hp=650
InputImagesPanel= uipanel('parent',F,'Title','','FontSize',12,...
             'BackgroundColor',Background,'BorderType','none',...
             'units','pixel','Position',[330,0,Wp,Hp]);
X=330 + Wp+30;
Wp2= 400;
Hp2=650;
% 
infoPanel= uipanel('parent',F,'Title','','FontSize',12,...
             'BackgroundColor',Background,'BorderType','none',...
             'units','pixel','Position',[X,0,Wp2,Hp2]);

         
 %% Button Groups
 X=50;
 W=220;
 H=30;
 Y=50;
 gap=40;
text1='Input image';
interpolate='bicubic';
DB=uicontrol('parent',panel,'string','CRAETE DB','callback',...
    ['Input_im=Load_image();'...
    'subplot(Axes1);'...
    'imshow(Input_im,[]);'...
    '[labels, numlabels] = slicmex(Input_im , 1000, 10);',...
    'im50= imresize(Input_im, 0.5, interpolate);',...
    '[labels50, numlabels50] = slicmex(im50 , 1000, 10);',...
    'title(text1);'],'FontSize',18, 'Position',[X 540 W H]);


PCAButton=uicontrol('parent',panel,'string','PERFORM PCA','callback',...
   [%Compute pattern Distinctness at 100% resolution
    'PatternSalience100 = PatternDistinctness( Input_im,labels,  numlabels);',...
    'PatternSalience50 = PatternDistinctness( im50,labels50,  numlabels50);',... %Compute pattern Distinctness at 50% resolution
    'PatternSalience50= imresize(PatternSalience50, size(PatternSalience100), interpolate);',...% Average of the two resolution distinctness
    'PatternSalience= ( PatternSalience100 + PatternSalience50)/2;',...
    'subplot(Axes2);'...% axes 3 and 4
    'imshow(PatternSalience, []);'...
    'title(p);'],'FontSize',18,'Position',[X 470 W H]);


face=uicontrol('parent',panel,'string','SELECT FACE','callback',...
   [% Compute Color Distinctness at diffrent resolution
   ' colorSalience100 = colorDistnictness( Input_im, labels, numlabels );',...%Compute color Distinctness at 50% resolution
    'colorSalience50 = colorDistnictness( im50,labels50,  numlabels50);',...% Average of the two resolution distinctness
    'colorSalience50= imresize(colorSalience50, size(colorSalience100), interpolate);',...
    'colorSalience= ( colorSalience100 + colorSalience50)/2;',...
    'subplot(Axes3);'...
    'imshow(colorSalience,[]);'...
    'title(text3);'],'FontSize',18,'Position',[X 340 W H]);

randomface=uicontrol('parent',panel,'string','RANDOM FACE','callback',...
    [
    'finalSliancy = combine_prior( PatternSalience ,  colorSalience);'...
    'subplot(Axes4);'...
    'imshow(finalSliancy);'...
    'title(salience);'],'FontSize',18,'Position',[X 270 W H]);

RECO=uicontrol('parent',panel,'string','RECOGNIZE','callback',...
    [
    'finalSliancy = combine_prior( PatternSalience ,  colorSalience);'...
    'subplot(Axes4);'...
    'imshow(finalSliancy);'...
    'title(salience);'],'FontSize',18,'Position',[X 100 W H+30]);


%% Matched list and How to use
X=30;
% Top Matched lists
Background=get(panel,'backgroundColor')
l= uicontrol('parent',infoPanel,'Style','text','Position',[X 620 Wp2-20 H],...
    'string','10 First Matched Face ', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12);
matcded = uicontrol('parent',infoPanel,'Style','text','Position',[X 370 Wp2-20 250],...
      'min',0,'max',2,'enable','inactive','background', [0.9 0.9 0.9],...
      'horizontalAlignment','left','FontSize',12); % create a listbox object
  set(matcded,'string',{'1. Yeman';'2. Minh';,...
    '3. Aleef';'3. Saed'});

% Match to Test image display
Ml= uicontrol('parent',infoPanel,'Style','text','Position',[X 300 Wp2-20 H],...
    'string','Exact Face Match ', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12);
matcded = uicontrol('parent',infoPanel,'Style','text','Position',[X 200 Wp2-20 100],...
      'min',0,'max',2,'enable','inactive','background', [0.9 0.9 0.9],...
      'horizontalAlignment','left','FontSize',12);



% User Help
label= uicontrol('parent',infoPanel,'Style','text','Position',[X 140 Wp2-20 H],...
    'string','How to use the software', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12); % create a listbox object
h = uicontrol('parent',infoPanel,'Style','text','Position',[X 20 Wp2-30 120],...
      'min',0,'max',2,'enable','inactive','background', [0.8 0.8 0.9],...
      'horizontalAlignment','left','FontSize',12); % create a listbox object
%str = {['']};
set(h,'string',{'1. Select Image';'2. Press Pattern Distinct';,...
    '3. Press Pattern Distinct';'3. Press Pattern and color distinctness to see final saliency'});
%set(h,'String',str) % display the string



%% *********** AXES TO DISPLAY images *****************
t2= uicontrol('parent',InputImagesPanel,'Style','text','Position',[X 312 200 H],...
    'string','Test Face ', 'background', Background,'FontWeight','bold',...
    'horizontalAlignment','center', 'FontSize',12);
Axes1=axes('parent',InputImagesPanel,'units','pixel','position',[0,350,280,250],'Box','off');
%set(Axes1,'color',Background);
Axes1.Color=Background;
%t2.background=Background;
Axes1.XTick=[]; Axes1.YTick=[];
t3= uicontrol('parent',InputImagesPanel,'Style','text','Position',[X 3 200 H],...
    'string','Matched Face ', 'background', Background,'FontWeight','bold',...
    'horizontalAlignment','center', 'FontSize',12);
Axes2=axes('parent',InputImagesPanel,'units','pixel','position',[0,40,280,270],'Box','off');
Axes2.Color=Background;
Axes2.XTick=[]; Axes2.YTick=[];
set(Axes1, 'box','off','XTickLabel',[],'XTick',[],'YTickLabel',[],'YTick',[])



