%=========================================================================
%       BY: YEMAN BRHANE HAGOS and
%           MINH VU
%=========================================================================
clear all; clc; close all

% -------------------------------------------------------------------------
% Initialize
dir_current = pwd;
dir_train = strcat(dir_current, '\Train');
dir_test = strcat(dir_current, '\Test');



%% ******************** CREATE fIGURE ****************************************

F= figure('Position',[100 50 1060 700],...
   'Name','',...
   'menubar','none','resize','off',...
   'NumberTitle','off');


Background=get(F,'Color');
%TITLE
 Title= uicontrol('parent',F,'Style','text','Position',[285 650 500 50],...
     'string','FACE RECOGNITION', 'background', Background ,...
     'horizontalAlignment','center', 'FontSize',14,'FontWeight','bold');
 
 
 
%% Panels

% FOR BUTTONS
panel = uipanel('parent',F,'Title','','FontSize',12,...
    'BackgroundColor',Background,...
    'units','pixel','Position',[0 0 350 650]);
% FOR AXES
Wp=350;
Hp=650;
InputImagesPanel= uipanel('parent',F,'Title','','FontSize',12,...
             'BackgroundColor',Background,'BorderType','none',...
             'units','pixel','Position',[355,0,Wp,Hp]);
X=330 + Wp+30;
Wp2= 350;
Hp2=650;
% 
infoPanel= uipanel('parent',F,'Title','','FontSize',12,...
             'BackgroundColor',Background,'BorderType','none',...
             'units','pixel','Position',[X,0,Wp2,Hp2]);

         
         
%% Button Groups
X=50;
W=220;
H=40;
Y=50;
gap=40;
fontsize=13;
str = 'string'

performpca_button=uicontrol('parent',panel,'string','Create DB / Perform PCA','callback',...
    ['[D , matrix_name] = createdatabase(dir_train);'...
    '[mean_train, centered_train, eigen_faces] = computeeigenface(D);'...
    ],'FontSize',fontsize, 'Position',[X 540 W H*2]);

%     'subplot(Axes1);'...
%     'imshow(Input_im,[]);'...

selecface_button = uicontrol('parent',panel,'string','Select Face','callback',...
    ['[image_in_path, image_in_name] = gui_selectimage();'...
    'image_in = imread(image_in_path);'...
    'subplot(Axes1);'...
    'imshow(image_in,[]);'...
    ],'FontSize',fontsize,'Position',[X 360 W H]);

randomface_button = uicontrol('parent',panel,'string','Random Face','callback',...
    ['[image_in_path, image_in_name] = gui_randomimage(dir_test);'...
    'image_in = imread(image_in_path);'...
    'subplot(Axes1);'...
    'imshow(image_in,[]);'...    
    ],'FontSize',fontsize,'Position',[X 300 W H]);

recognition_button = uicontrol('parent',panel,'string','RECOGNIZE','callback',...
    ['image_out_name = recognizematch(image_in_path, mean_train, centered_train, eigen_faces, matrix_name, 10);'...
    'image_out_path = gui_generatepath(dir_train, image_out_name);'...
    'image_out = imread(image_out_path);'...
    'subplot(Axes2);'...
    'imshow(image_out,[]);'...
    '[image_out_name_display, image_matched_display] = gui_addandfindranking (image_out_name, image_in_name);'...
    'set(matcded2,str,image_out_name_display);'...
    'set(matcded,str,image_matched_display);'...
    ],'FontSize',fontsize,'Position',[X 100 W H*2]);


%% Matched list and How to use
X=30;
H = H -15;
% Top Matched lists
Background=get(panel,'backgroundColor');
l= uicontrol('parent',infoPanel,'Style','text','Position',[X 620 Wp2-20 H],...
    'string','10 First Matched Face ', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12);
matcded2 = uicontrol('parent',infoPanel,'Style','text','Position',[X 370 Wp2-20 250],...
    'min',0,'max',2,'enable','inactive','background', [0.9 0.9 0.9],...
    'horizontalAlignment','left','FontSize',12); % create a listbox object

% Match to Test image display
Ml= uicontrol('parent',infoPanel,'Style','text','Position',[X 300 Wp2-20 H],...
    'string','Found face at position(s)', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12);
matcded = uicontrol('parent',infoPanel,'Style','text','Position',[X 200 Wp2-20 100],...
      'min',0,'max',2,'enable','inactive','background', [0.9 0.9 0.9],...
      'horizontalAlignment','left','FontSize',12);



% User Help
label= uicontrol('parent',infoPanel,'Style','text','Position',[X 140 Wp2-20 H],...
    'string','How to use the software', 'background', [0.5 0.5 0.5],...
    'horizontalAlignment','center', 'FontSize',12); % create a listbox object
h = uicontrol('parent',infoPanel,'Style','text','Position',[X 20 Wp2-30 120],...
      'min',0,'max',2,'enable','inactive','background', [0.8 0.8 0.9],...
      'horizontalAlignment','left','FontSize',12); % create a listbox object
%str = {['']};
set(h,'string',{'1. Press Create DB / Perform PCA';'2. Select Face or Random Face';,...
    '3. Press Recognize'});
%set(h,'String',str) % display the string



%% *********** AXES TO DISPLAY images *****************
t2= uicontrol('parent',InputImagesPanel,'Style','text','Position',[X+45+20 320 200 H],...
    'string','Test Face ', 'background', Background,'FontWeight','bold',...
    'horizontalAlignment','center', 'FontSize',12);
Axes1=axes('parent',InputImagesPanel,'units','pixel','YGrid','off',...
    'XGrid','off','position',[25,360,350,250],'Box','off');
color = get(F,'Color');
set(Axes1,'YColor',color,'TickDir','out')


Axes1.Color=Background;
Axes1.XTick=[]; Axes1.YTick=[];
t3= uicontrol('parent',InputImagesPanel,'Style','text','Position',[X+45+20 15 200 H],...
    'string','Matched Face ', 'background', Background,'FontWeight','bold',...
    'horizontalAlignment','center', 'FontSize',12);
Axes2=axes('parent',InputImagesPanel,'units','pixel','position',[25,50,350,250],'Box','off');
Axes2.Color=Background;
set(Axes2,'YColor',color,'TickDir','out')
Axes2.XTick=[]; Axes2.YTick=[];
set(Axes1, 'box','off','XTickLabel',[],'XTick',[],'YTickLabel',[],'YTick',[])